# This dockerfile creates an environment suitable for building on jenkins
# Note that changes to this file will take two jenkins builds to reflect -- the first will
# pull the change, then the second will use the pulled change to rebuild the dockerfile

FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy

# Also add python3
RUN apt-get update \
    && apt-get install -y \
        python3 \
        zip \
	    gettext \
    && rm -rf /var/lib/apt/lists/*
